### ISSUE TITLE
Ignoring whitespace in trans blocks

### ISSUE THREAD

**Issue by Anahkiasen** [twigphp/Twig-extensions#111]
I want to translate a large chunk of text:

``` twig
{% trans %}
    Some piece of<br>
    Text
{% endtrans %}
```

It gets recognized as the following key : `\tSome piece of <br>\n\tText`. Any way to make the trans block ignore the whitespace without having remove it all and sacrifice the visibility of my view ?

**Comment by fabpot** [comment]
I'm closing all issues/PRs on the i18n extension as I don't use it and I don't have time to maintain it anymore. This repository will be soon deprecated in favor of the `twig/*-extra` packages, but i18n wont be transferred. If anyone wants to work on the i18n extension, I would recommend to take the code from here and host it on a new repository.
