### ISSUE TITLE
localized number formatter settings

### ISSUE THREAD

**Issue by Orion98MC** [twigphp/Twig-extensions#125]
Hi Fabien,
Is it possible to add custom settings to the formatter used by the localizednumber filter?

For instance I would require to restrain the number of decimals between 0 and 2. The problem I have is that the Intl extension class uses functions outs of the class scope, which could not be overridden ( twig_localized_number_filter, and twig_get_number_formatter).

Maybe I'm mistaken, but can you tell me how to achieve this goal?

Regards,
Thierry

**Comment by naitsirch** [comment]
Does #134 solve your issue?
