### ISSUE TITLE
Adding "with" keyword to i18n

### ISSUE THREAD

**Issue by Dsls** [twigphp/Twig-extensions#13]
When using complex translations with parameters, we currently need to declare temporary variables for each parameter.

Example :

<pre>
{% set name = name|capitalize %}
{% set site_url = '&lt;a href="http://www.mysite.com" alt="mysite"&gt;my website&lt;/a&gt;' %}
{% trans %}
    Hello {{ name }}! Welcome to {{ site_url }}.
{% endtrans %}
</pre>

Using a "with" syntax similar to "include" tag could be an enhancement for this :

<pre>
{% trans with {'name': name|capitalize, 'site_url':'&lt;a href="http://www.mysite.com" alt="mysite"&gt;my website&lt;/a&gt;'} %}
    Hello {{ name }}! Welcome to {{ site_url }}
{% endtrans %}
</pre>

That would also enable to have a restrict context for translation (through the "only" keyword) , in the case we do not want to give access to other variables.

**Comment by fabpot** [comment]
I'm closing all issues/PRs on the i18n extension as I don't use it and I don't have time to maintain it anymore. This repository will be soon deprecated in favor of the `twig/*-extra` packages, but i18n wont be transferred. If anyone wants to work on the i18n extension, I would recommend to take the code from here and host it on a new repository.
