### ISSUE TITLE
How to install it ?

### ISSUE THREAD

**Issue by quentincurtet** [twigphp/Twig-extensions#140]
Hi,

I installed this using composer but i don't know where to put : 
$twig = new Twig_Environment($loader);
$twig->addExtension(new Twig_Extensions_Extension_Intl());

And i don't find it in the documentation !

Help me please !

**Comment by stof** [comment]
The line ``$twig = new Twig_Environment($loader);`` is the one where you instantiate Twig itself. Locate it in your code, and this is the place where registering the extension should be done.

If you use a framework which provides a Twig integration, this integration probably provides a way to register extensions, which is what you would need to look for.

**Comment by quentincurtet** [comment]
I am working with symfony 2.7
Should i put it in my controller ?

I am completely lost, i just want to put the correct format with intl but i can't use it

**Comment by stof** [comment]
this is exactly the case I describe above. Given that Symfony handles the twig instantiation itself, it provides a way to register extensions in the setup it does. And the Symfony documentation explains the way to register twig extensions in a Symfony setup: http://symfony.com/doc/current/cookbook/templating/twig_extension.html shows how to write and register an extension. In the case of the ``Twig_Extensions_Extension_Intl``, the code is already written, so you only need to to the second step. (And http://symfony.com/doc/current/reference/dic_tags.html#twig-extension concerns it too)

**Comment by quentincurtet** [comment]
Ok but i need an "use" statement but i don't know what to put in my file?

**Comment by stof** [comment]
which use statement are you talking about ?

**Comment by quentincurtet** [comment]
i put the service in my config.yml but i have an error : 
```
Attempted to load class "Twig_Extensions_Extension_Intl" from the global namespace.
Did you forget a "use" statement?
```

**Comment by stof** [comment]
Well, have you installed the twig-extensions package in your project ? It looks like the extension class cannot be autoloaded.

This message is displayed by Symfony when it cannot find the class after autoloading, pointing at a potential mistake. But in this case, loading it from the global namespace is logical, as the class is in the global namespace.

**Comment by quentincurtet** [comment]
Yes i installed it.
 
It seems that Symfony is looking for the twig extension class in the cache, i got this fatal error : 
```
Fatal Error: Class 'Twig_Extensions_Extension_Intl' not found {"type":1,"file":"/home/idci/Workspace/symposium2/app/cache/de_/ap_DevDebugProjectContainer.php","line":3398...
```

**Comment by stof** [comment]
Well, the cache file is the place where it will try to use the class, which is totally logical.

Are you using the composer autoloader or a custom autoloader ?

**Comment by quentincurtet** [comment]
The composer one, i am not using any custom autoloader

**Comment by quentincurtet** [comment]
If it can help my application is dockerized, but i am running composer command inside the container so i don't see in which way it could be an issue

**Comment by quentincurtet** [comment]
Excuse me, but i put the extension in the bad composer.json i am a noob...
Thanks for the help!

**Comment by stof** [comment]
Please close this issue then (I cannot do it myself. I'm not collaborator on the repo)

**Comment by diimpp** [comment]
For who are looking into the same question, in symfony it should be registered as service.

For example for `intl`
```yaml
# app/config/services.yml
services:
    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }
``
http://stackoverflow.com/a/28410279

**Comment by KojoEnch** [comment]
In **Symfony 4.3** with all dependencies updated , this is now into `config/packages/twig_extensions.yaml` , just uncomment the line(s) for each extension you wish to activate : 
```
services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true

    # Uncomment any lines below to activate that Twig extension
    #Twig\Extensions\ArrayExtension: ~
    #Twig\Extensions\DateExtension: ~
    #Twig\Extensions\IntlExtension: ~
    #Twig\Extensions\TextExtension: ~

```

**Comment by luispabon** [comment]
In addition to @KojoEnch comment above, you also need to add `twig/extensions` to your `composer.json`
