### ISSUE TITLE
Translation of Empty String

### ISSUE THREAD

**Issue by alecsammon** [twigphp/Twig-extensions#15]
Example 

{% set foo = "" %}
{% trans foo %}

This returns the header information of the gettext mo file. Although this is standard behavior for gettext it may not be desirable. Suggest modifying to just return an empty string.

**Comment by fabpot** [comment]
I'm closing all issues/PRs on the i18n extension as I don't use it and I don't have time to maintain it anymore. This repository will be soon deprecated in favor of the `twig/*-extra` packages, but i18n wont be transferred. If anyone wants to work on the i18n extension, I would recommend to take the code from here and host it on a new repository.
