### ISSUE TITLE
Problem with localizednumber('duration')

### ISSUE THREAD

**Issue by sc0rp10** [twigphp/Twig-extensions#150]
I have 'ru_RU' locale and I want to format duration: `{{ 10240 | localizednumber('duration') }}`
Expected result is _2:50:40_, but i got _10 240_.
I played with INTL PHP provider and see that NumberFormatter doesn't have full pattern for ru_RU:

```
$en_formatter = new \NumberFormatter('en_US', \NumberFormatter::DURATION);
var_dump($en_formatter->getPattern());
$ru_formatter = new \NumberFormatter('ru_RU', \NumberFormatter::DURATION);
var_dump($ru_formatter->getPattern());
```

And I got:

```
string(544) "%with-words:
    0: 0 seconds;
    1: 1 second;
    2: =#0= seconds;
    60/60: <%%min<;
    61/60: <%%min<, >%with-words>;
    3600/60: <%%hr<;
    3601/60: <%%hr<, >>>;
%%min:
    0: 0 minutes;
    1: 1 minute;
    2: =#0= minutes;
%%hr:
    0: 0 hours;
    1: 1 hour;
    2: =#0= hours;
%in-numerals:
    0: =#0= sec.;
    60: =%%min-sec=;
    3600: =%%hr-min-sec=;
%%min-sec:
    0: :=#00=;
    60/60: <#0<>%%min-sec>;
%%hr-min-sec:
    0: :=#00=;
    60/60: <#00<>%%hr-min-sec>;
    3600/60: <#,##0<:>>>;
%d
```

```
string(27) "%duration:
    0: =#,##0=;
"
```

As I see, ru_RU locale isn't full and don't support any of formats.
Maybe need force locale to en_US, if `$style == 'duration'` in `Twig_Extensions_Extension_Intl`?

**Comment by stof** [comment]
I'm not sure we should force it, as it would mean things would not work if a fix is implemented in PHP.

However, I suggest you to report a bug to PHP about this.

**Comment by sc0rp10** [comment]
@stof but report in PHP useless and they don't fix this in reasonable time. Twig can handle and fix it for 3 LoC in function `twig_localized_number_filter`.

**Comment by stof** [comment]
@sc0rp10 the report in PHP is not useless as you could hope that future versions of PHP would support the ru_RU locale.

and forcing the locale to ``en_US`` in the Twig extension would be a sensible case only if **all** other locales are broken. Otherwise it is breaking assumptions.

**Comment by sc0rp10** [comment]
I've check for broken locales in this case: https://gist.github.com/sc0rp10/d55f4b5374d5d401059b
168 of 683 locales are broken and Twig can fix it. Why don't do it, if it possible?

**Comment by stof** [comment]
Well, as you can see, the fix is not as simple as forcing ``en_US`` all the time, because this would break 515 working locales.

and in any case, this should still be reported to PHP to reduce the list of broken locales in the future
