### ISSUE TITLE
[RFC] Pre filter

### ISSUE THREAD

**Issue by lyrixx** [twigphp/Twig-extensions#154]
Hello.

Quite often, I have to write documentation with `pre` section.
But because of spaceless managment of twig, we have to write something like:
```
                        {# yes, it's super indented on purpose #}
                        <pre>
My first line of doc
Another line of doc
They all have to start at the very begining of the template line
    This line is indented on purpose
                        </pre>
```

In chef/ruby (sorry), they have something to automatically remove leading space.
With that we can write:

```
                        {# yes, it's super indented on purpose #}
                        <pre>
                            {% filter pre %}
                                My first line of doc
                                Another line of doc
                                They all have to start at the very begining of the template line
                                    This line is indented on purpose
                            {% endfilter %}
                        </pre>
```

What do you think ?

**Comment by stof** [comment]
Well, this could make sense (for Twig-extensions, not for the core). but ``pre`` is a weird name. ``unindent`` would be easier to understand.
do you have a working implementation of such filter ?

**Comment by lyrixx** [comment]
Not yet . but I can work on it.

**Comment by lyrixx** [comment]
Looks like there is not a big need on this one. Closing it.
