### ISSUE TITLE
standard symfony (2.7.6) + standard twig extensions (1.3) gives deprecation warning

### ISSUE THREAD

**Issue by rbaarsma** [twigphp/Twig-extensions#157]
steps to reproduce:
```bash
symfony new project
cd project
composer require twig/extensions
composer update
php app/console server:run
```

Go to http://127.0.0.1:8000 and directly spot the deprecation warning:

```php
DEPRECATED - Defining the initRuntime() method in the "form" extension is deprecated. Use the `needs_environment` option to get the Twig_Environment instance in filters, functions, or tests; or explicitly implement Twig_Extension_InitRuntimeInterface if needed (not recommended). -

    Called from Twig_Environment::initRuntime() at line 408
    Called from Twig_Environment::loadTemplate() at line 126
    Called from TwigEngine::load() at line 50
    Called from TwigEngine::render() at line 72
    Called from TwigEngine::render() at line 97
    Called from TwigEngine::renderResponse() at line 176
    Called from Controller::render() at line 19
    Called from DefaultController::indexAction()
    Called from call_user_func_array() at line 3109
    Called from HttpKernel::handleRaw() at line 3071
    Called from HttpKernel::handle() at line 3222
    Called from ContainerAwareHttpKernel::handle() at line 2444
    Called from Kernel::handle() at line 29
```

The issue is is visible in the composer.lock

            "name": "twig/twig",
            "version": "v1.22.3",

became

           "name": "twig/twig",
            "version": "v1.23.1",

Which apparently symfony 2.7.6 is not ready for.

**Comment by stof** [comment]
Well, a deprecation is not breaking anything (it just put stuff in the logs). And the Symfony codebase has already been updated to account for this deprecation (it will be part of the next 2.3 and 2.7 releases, and is already part of the 2.8-beta1 release)

**Comment by stof** [comment]
anyway, this has nothing to do with the Twig-extensions repository. It is not involved in this message at all

**Comment by rbaarsma** [comment]
Well if it's fixed soon maybe it's a non-issue. Just thought that maybe twig/extensions was walking too far ahead on the twig version and the standard ```composer require twig/extensions` should give a version without deprecations in standard symfony.

I had no deprecations before, and after I installed twig extensions I have 5, 1 is this one, 4 more from jms/translation-bundle. I think stable versions should be deprecation free, don't you agree?

**Comment by ninsuo** [comment]
No, minor versions should be backward compatible. But if a feature is obsolete (replaced by something better, but still available for BC), we encourage people to use the better way by firing a deprecation notice. By following recommendations, it becomes really easy to upgrade to a major version.
