### ISSUE TITLE
Insert Global variable in all template

### ISSUE THREAD

**Issue by roji430** [twigphp/Twig-extensions#161]
i am new to Twig..
my question is how to implement set of global variable to use in all template..
like App version,App Title,App name,etc ...
then after i want to call it like normal variable in all template example
<code>{{ App version}}</code>

thanks in adavance

**Comment by lyrixx** [comment]
See the doc: http://twig.sensiolabs.org/doc/advanced.html#globals or http://twig.sensiolabs.org/doc/advanced.html#id1
