### ISSUE TITLE
TimeAgoExtension Error

### ISSUE THREAD

**Issue by vortexgin** [twigphp/Twig-extensions#165]
I have updated twig tonight and show this error : 

Catchable Fatal Error: Argument 1 passed to Salavert\Twig\Extension\TimeAgoExtension::__construct() must be an instance of Symfony\Component\Translation\IdentityTranslator,
  instance of Symfony\Bundle\FrameworkBundle\Translation\Translator given, called in /Users/admin/ds-2015/app/cache/de_/ap_DevDebugProjectContainer.php on line 2227 and define
  d in /Users/admin/ds-2015/vendor/salavert/time-ago-in-words/src/Salavert/Twig/Extension/TimeAgoExtension.php line 21

**Comment by stof** [comment]
``Salavert\Twig\Extension\TimeAgoExtension`` has nothing to do with this repository. It is part of the ``salavert/time-ago-in-words`` composer package: https://packagist.org/packages/salavert/time-ago-in-words

**Comment by vortexgin** [comment]
ok, sorry. i have change on this part and this running well 

```
//use Symfony\Component\Translation\IdentityTranslator;
use Symfony\Component\Translation\Translator;

class TimeAgoExtension extends \Twig_Extension
{
    /**
     * @var IdentityTranslator
     */
    protected $translator;

    /**
     * Constructor method
     *
     * @param IdentityTranslator $translator
     */
    public function __construct(Translator $translator)
```

**Comment by stof** [comment]
This still does not have anything to do with this issue.

On a side note, you issue is that you are typehinting the Translator implementation instead of TranslatorInterface, which means you are incompatible with other implementations (and IdentityTranslator is a separate implementation of the interface)
