### ISSUE TITLE
localizedcurrency pattern feature request

### ISSUE THREAD

**Issue by alexseif** [twigphp/Twig-extensions#167]
This is a great library, but an issue I have is that it returns the current output
"RUB8,000.00"
While I appreciate this a lot, I'd like to add a space between the currency and value, after some digging, I was able to do that with modifiying the twig_localized_currency_filter function like the following

```
function twig_localized_currency_filter($number, $currency = null, $locale = null)
{
    $formatter = twig_get_number_formatter($locale, 'currency');
    $formatter->setPattern(str_replace('¤#', '¤ #', $formatter->getPattern()));
    return $formatter->formatCurrency($number, $currency);
}
```

I thought it could be convenient to override a pattern configuration write below where I set the locale in my symfony parameters.yml
and/or add a new a parameter to the above function

**Comment by glen-84** [comment]
You also need access to the formatter in order to set attributes, for example:

```php
$numberFormatter = new NumberFormatter('en-US', NumberFormatter::CURRENCY);
$numberFormatter->setAttribute(NumberFormatter::FRACTION_DIGITS, 0);

echo $numberFormatter->formatCurrency('45.99', 'USD');
```

... for removing/rounding decimals.

**Comment by alexseif** [comment]
So what are we going to do about it 😆

**Comment by fabpot** [comment]
This is implemented as part of https://github.com/twigphp/Twig/pull/3108
