### ISSUE TITLE
[RFC] Make Intl extension work when no PHP Intl extension is available

### ISSUE THREAD

**Issue by javiereguiluz** [twigphp/Twig-extensions#177]
### Context

I know that failing hard is the right thing to do for most errors. For example, if `date.timezone` is not set in php.ini, Twig refuses to work. But the solution to this problem is trivial: change one file, restart, done!

However, when you don't have the PHP `intl` extension, for most people there is no solution possible. You can't install that damn extension in a simple way.

### Problem

If you don't have the PHP intl extension, the Twig Intl extension fails hard and the application explodes.

### Proposal

In the Symfony Demo app we use the Twig Intl extension, but we've made it work for people who don't have the `intl` PHP extension: https://github.com/symfony/symfony-demo/pull/335/files

My (crazy) proposal: could we update Twig Intl to fallback to English-only when the PHP intl is not available? As you can see, it's a matter of adding a few lines of code and the maintenance will be minimal.

**Comment by stof** [comment]
Well, why not relying on the symfony/intl polyfill ?

**Comment by javiereguiluz** [comment]
@stof for this repo it's not possible to use the polyfill because it uses PHP 5.3 and Twig requires 5.2.

For the Demo app I've tried to use `symfony/intl`, `symfony/polyfill-intl-icu`, etc. with no luck. I suffer all kinds of errors:

![intl_error_1](https://cloud.githubusercontent.com/assets/73419/15175302/ed729870-1765-11e6-9596-2af990795985.png)

![intl_error_2](https://cloud.githubusercontent.com/assets/73419/15175303/f0340bd4-1765-11e6-8698-ec390a2b7d36.png)

Maybe @nicolas-grekas can help us here because he created the polyfills.

**Comment by sstok** [comment]
If you use Composer then you already have at least PHP 5.3 and Intl support was added in PHP 5.3 :)
So in that case this is not a problem.

**Comment by javiereguiluz** [comment]
Closing it because the new Intl extension of the Twig bundle (see https://github.com/symfony/symfony/pull/20053) will make this irrelevant.
