### ISSUE TITLE
Wordwrap `preserve` bug.

### ISSUE THREAD

**Issue by SamMousa** [twigphp/Twig-extensions#179]
When using the `wordwrap` with `preserve` set to true, there is no wordwrapping happening.

For the `truncate` filter, `preserve` respect word boundaries, for `wordwrap` it respects line boundaries but doesnt wrap, which in opinion doesn't make sense.

Example:

```
{{ "This is a very long sentence, so long in fact, that it does not fit on one line." | wordwrap(20, "\n", false) }}
Output:
This is a very long 
sentence, so long in 
fact, that it does n
ot fit on one line.

{{ "This is a very long sentence, so long in fact, that it does not fit on one line." | wordwrap(20, "\n", true) }}

This is a very long sentence, so long in fact, that it does not fit on one line.
```

Ideally there should be some more options for this filter (I'm willing to implement these if you agree), for example, it is often the case that you want to respect word boundaries, respect existing line breaks and round down or up.

```
{{ "This is a very long sentence, so long in fact, that it does not fit on one line." | wordwrap(20, "\n", true, respectWordBoundaries="up") }}

Result:
This is a very long
sentence, so long in
fact, that it does not
fit on one line.

{{ "This is a very long sentence, so long in fact, that it does not fit on one line." | wordwrap(20, "\n", true, respectWordBoundaries="down") }}

Result:
This is a very long
sentence, so long in
fact, that it does 
not fit on one line.
```

Regarding the generic `preserve` parameter, I think for wordwrapping it should still wrap long lines after preserving the existing new lines.

Note: In the above example I have used the named parameter notation to make it more readable without having to give pseudo code for the of implementation.

**Comment by stof** [comment]
the mbstring-based implementation of ``wordwrap`` indeed looks broken.

**Comment by macwinnie** [comment]
*push*
implementing this issue would solve some problems for me, too ...

**Comment by gjuric** [comment]
I got affected by this as well and I am looking into this.

Just wanted to ask if there a better way to ease the testings of code that uses some extension vs code that doesn't?

Currently the function definition is overwritten and I manually switch the 

    if (function_exists('mb_get_info')) {

to 

    if (!function_exists('mb_get_info')) {

**Comment by gjuric** [comment]
Also, there is an issue with the current tests for truncate where they work if you have mb extensions and one of them fails if you do not.

**Comment by shakaran** [comment]
Any update with this bug? I am affected too

**Comment by fabpot** [comment]
I'm closing this issue as we now have native support (including proper Unicode support) in the string Twig extension: see https://twig.symfony.com/u
