### ISSUE TITLE
Extracting template strings no longer working?

### ISSUE THREAD

**Issue by bjornpost** [twigphp/Twig-extensions#181]
I'm trying to create a `messages.pot` file for my application using the [workflow described in the docs](http://twig.sensiolabs.org/doc/extensions/i18n.html#extracting-template-strings). Unfortunately, I can't get this to work. I can render the cached version of my templates, but when running `xgettext`, no strings are recognized.

After inspecting a cached template, I see calls being made to

```
echo $this->env->getExtension('translator')->getTranslator()->trans("Yadda", array(), "messages");
```

I guess `xgettext` only looks for calls to `gettext()`, `dcgettext()`, etc. Am I missing something here? How to fix this?

(silex 2.0.2-dev, twig 1.24.1, twig-bridge 3.0.7)

**Comment by bjornpost** [comment]
Anyone?

**Comment by bjornpost** [comment]
So for anyone who ends up here looking for a solution as well: I gave up on fixing things with `xgettext`. Instead I [made a small node js script](https://gist.github.com/bjornpost/aa2373f6c450b9a8c0fde7becaff5683) (based on [this](http://pastebin.com/WSDsABfz)) with extracts translateable strings. It isn't pretty, nor feature complete, but it gets the basic job done.

**Comment by fabpot** [comment]
I'm closing all issues/PRs on the i18n extension as I don't use it and I don't have time to maintain it anymore. This repository will be soon deprecated in favor of the `twig/*-extra` packages, but i18n wont be transferred. If anyone wants to work on the i18n extension, I would recommend to take the code from here and host it on a new repository.
