### ISSUE TITLE
truncate filter option to preserve whole words while not exceeding word limit

### ISSUE THREAD

**Issue by rayrigam** [twigphp/Twig-extensions#185]
The truncate filter should have an option to preserve whole words while not exceeding the word limit. From my point of view that option is more useful than the one given (which can preserve whole words but at the expense of exceeding the word limit).

**Comment by rayrigam** [comment]
This is one way to do it (including the separator length within the limit):
```
public function truncateWhole($string, $limit, $separator = '...')
{
    if (strlen($string) > $limit) {
        $newlimit = $limit - strlen($separator);
        $s = substr($string, 0, $newlimit + 1);
        return substr($s, 0, strrpos($s, ' ')) . $separator;
    }
    return $string;
}
```
I used the following reference: http://stackoverflow.com/a/1233360

**Comment by ccbrown** [comment]
+1

When we truncate text, we do it because we can't allow it to exceed a certain width. A truncate function that can't make that guarantee is completely useless to us.

**Comment by fabpot** [comment]
I'm closing this issue as we now have native support (including proper Unicode support) in the string Twig extension: see https://twig.symfony.com/u
