### ISSUE TITLE
Using time_diff with gettext returns no count or plural ?

### ISSUE THREAD

**Issue by hammat** [twigphp/Twig-extensions#186]
Hi,

I'm working on a fuelphp project. I've set up Twig and these extensions in order to use Date & i18n (with gettext files) functions.

Everything was going well until now where I'm struggling myself with the time_diff filter.
Actually time_diff is working well until I tried to translate its output using gettext.

- Without giving a Translator to the extension `{{ foo | time_diff }}` will return a correct string in english with the harcoded units and plural ie `[0|9] [day|...|year][s] ago`

- While giving a Translator to the extension, the same `{{ foo | time_diff }}` will only return only the id (ie `diff.ago.month`) to be filtered with gettext using `trans`. There is no number or plural to be used.

Am I doing something wrong ?

**Comment by stof** [comment]
This is probably because your translator implementation does not have translations for the translation keys used by the extension

**Comment by hammat** [comment]
Actually I'd though it does since using the `trans` filter will translate the key correctly.
`{{ date_in_march | time_diff }}` => `diff.ago.month` (without '4' and without 'month**s**')
`{{ date_in_march | time_diff | trans }}` => `month`

**Comment by stof** [comment]
@hammat I'm talking about the Translator instance passed into your Date extension.

**Comment by hammat** [comment]
@stof Allright, thanks for the clue !

I've oriented my research on the translator as you told me and I gave an empty Translator instead of adding the right loader and resources like described here https://symfony.com/doc/current/components/translation/introduction.html, my bad.
I'd suggest to link it in the date extension just in case anyway.

Thanks a lot again,
