### ISSUE TITLE
Localizeddate medium filter in Spanish does not contain month in text.

### ISSUE THREAD

**Issue by ambroisemaupate** [twigphp/Twig-extensions#187]
Is it normal than Spanish _medium_ date format keeps only numbers like if it was _short_ syntax?

http://twigfiddle.com/sb4df1

`{{ 'now'|localizeddate('medium', 'medium', 'es_ES') }}` ==> `9/9/2016 11:08:32`

is the same as

`{{ 'now'|localizeddate('short', 'medium', 'es_ES') }}` ==> `9/9/2016 11:08:32`

**Comment by KhaledTo** [comment]
HI @ambroisemaupate. It's not related to Twig Extensions but to the Intl extension. If you type this : 

```
<?php

$DateTime = new DateTime();
$IntlDateFormatter = new IntlDateFormatter(
    'es_ES',
    IntlDateFormatter::MEDIUM,
    IntlDateFormatter::MEDIUM
);
echo $IntlDateFormatter->format($DateTime);
```

You'll get the same format as the one you got.
