### ISSUE TITLE
Deprecation warning with Twig 1.25

### ISSUE THREAD

**Issue by trendfischer** [twigphp/Twig-extensions#188]
Since updating to twig 1.25 I got a deprecation warning:

> Using "null" for the value of node "count" of "Twig_Extensions_Node_Trans" is deprecated since version 1.25 and will be removed in 2.0.

It results in using the `trans` block of `Twig_Extensions_Extension_I18n` like this:

     <p>{% trans "Test" %}</p>

**Comment by SpacePossum** [comment]
This seems an issue with the extensions, please report it @ https://github.com/twigphp/Twig-extensions

**Comment by trendfischer** [comment]
Well ... yes, the url part in the browser for this issue seems to be the right one???

**Comment by SpacePossum** [comment]
lol, sorry man misread!

**Comment by fabpot** [comment]
see #189

**Comment by trendfischer** [comment]
Tested the patch (or better said: the HEAD of master) and it works, thanks :smile:
