### ISSUE TITLE
Document link is broken in the README.rst

### ISSUE THREAD

**Issue by gmclelland** [twigphp/Twig-extensions#201]
Just letting someone know the "Documentation" link that points to http://twig.sensiolabs.org/doc/2.x/extensions/index.html in the README.rst no longer works.

**Comment by vojtasvoboda** [comment]
🆙

**Comment by gmclelland** [comment]
@vojtasvoboda are you saying it is fixed now?  I checked and didn't see any difference.

**Comment by fabpot** [comment]
Indeed, I've removed Twig extensions documentation from the official website.

**Comment by tzetze** [comment]
Will it be documented anywhere else? Or these extensions aren't supported anymore?

**Comment by tzetze** [comment]
Okay, docs are available here: http://twig-extensions.readthedocs.io/en/latest/

**Comment by gmclelland** [comment]
Thanks everyone!
