### ISSUE TITLE
Unclear error message if PHP intl extension is missing

### ISSUE THREAD

**Issue by malaire** [twigphp/Twig-extensions#210]
After installing extensions and adding only this line to otherwise working code:

    $twig->addExtension(new Twig_Extensions_Extension_Intl());

I get following error:

    The intl extension is needed to use intl-based filters.,

I am not even trying to use the extension yet, just added that one line to load the extension.

OS is Debian Stretch with PHP 7.0 and following composer.json:

    {
        "require": {
            "twig/twig": "2.4.3",
            "twig/extensions": "^1.5"
        }
    }

**Comment by malaire** [comment]
And I just realized error is speaking about PHP extension and not about Twig extension.

I'm leaving this open with different title since I think the error message should be fixed.

**Comment by stof** [comment]
Well, you *are* trying to use the Twig_Extensions_Extension_Intl extension in your project as you register it. So checking its dependency still makes sense.

**Comment by fabpot** [comment]
Closing as there is no bug here.
