### ISSUE TITLE
localizednumber doesn't support feminine ordinal numbers

### ISSUE THREAD

**Issue by malaire** [twigphp/Twig-extensions#211]
Ordinal numbers e.g. in Italian can be feminine or masculine, but localizednumber doesn't support this distinction.

Here is example PHP code to show the difference:

    $m = new NumberFormatter('it', NumberFormatter::ORDINAL);
    $m->setTextAttribute(NumberFormatter::DEFAULT_RULESET, "%digits-ordinal-masculine");
    var_dump($m->format(10));

    $f = new NumberFormatter('it', NumberFormatter::ORDINAL);
    $f->setTextAttribute(NumberFormatter::DEFAULT_RULESET, "%digits-ordinal-feminine");
    var_dump($f->format(10));

Output:

    string(4) "10º"
    string(4) "10ª"

**Comment by fabpot** [comment]
This is going to be possible via https://github.com/twigphp/Twig/pull/3108
