### ISSUE TITLE
localized currency renders nothing

### ISSUE THREAD

**Issue by hunterallen** [twigphp/Twig-extensions#212]
I've used this extension for several months, then moved it to my linux server and now localized currency doesn't display anything. 

`<h3>Sale Total: {{ order.finalPrice|localizedcurrency('USD') }} </h3>`

Returns

`<h3>Sale Total: </h3>`

I don't get any errors and there's nothing in the logs about it. I've tried to remove and reinstall but it doesn't seem to work.

**Comment by lmanzurv** [comment]
Maybe you're missing the locale. For me, it was that. So do 

`<h3>Sale Total: {{ order.finalPrice|localizedcurrency('USD', 'en') }} </h3>`

Instead of

`<h3>Sale Total: {{ order.finalPrice|localizedcurrency('USD') }} </h3>`
