### ISSUE TITLE
localizeddate adds one hour to every timezone

### ISSUE THREAD

**Issue by mrAndersen** [twigphp/Twig-extensions#214]
Hi, i have some strange problem, may be this can be concerned as bug

{{ material.published | localizeddate('short', 'short') }}
returns 16.08.17, 14:14 when symfony global timezone is set to Berlin
```
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    date:
        timezone: Europe/Berlin
```

and 16.08.17, 14:14 when used Moscow,

but actual datetime stored in database in UTC timezone is 16.08.17, 12:14, so it always adds additional hour

**Comment by mrAndersen** [comment]
I have done some debugging, and just before filter returns it's value, it has correct date, and then, somehow it adds additional hour

[http://i.imgur.com/71nu0ht.png](url)

**Comment by stof** [comment]
Well, 12:14 in UTC is perfectly fine as 14:14 in Berlin timezone in August (as the Berlin timezone is in summer time at that date, and so is 2 hours ahead of UTC). I see no bug here.

**Comment by fabpot** [comment]
Closing as time should always be interpreted with the timezone.
