### ISSUE TITLE
Precise value for number of digits for currency.

### ISSUE THREAD

**Issue by chadyred** [twigphp/Twig-extensions#217]
Hello,

**WHY ?**

Actually no filter allow us to choose if we allow digits or not when currency is use.

Everytime, each digits parts is here, and I want to choose if I keep it or not.

Example; 

`10000|localizedcurrency('SWF`)

for Swiss peaple become 

`SWF 10'000.00.`

No digits needed for me so I use like : 

`10000localizedcurrency('SWF', 0)`

 for Swiss people become 

`SWF 10'000`

**HOW  ?**

Adding a parameters to filter directly on constant of formatter before format.

**PR**

https://github.com/twigphp/Twig-extensions/pull/216

**Comment by fabpot** [comment]
Closing as there is a related PR.
