### ISSUE TITLE
localizeddate filter error for some timezone

### ISSUE THREAD

**Issue by fjude** [twigphp/Twig-extensions#227]
Hi !

If i use the filter localizeddate() with these two TZ : 
- Asia/Tomsk
- Europe/Kirov

I got this error :
<img width="1049" alt="capture d ecran 2018-07-08 a 10 37 53" src="https://user-images.githubusercontent.com/1249385/42418176-18715b90-829b-11e8-950a-e0b66f443cec.png">

My code : 
<img width="1001" alt="capture d ecran 2018-07-08 a 10 38 17" src="https://user-images.githubusercontent.com/1249385/42418177-18895bbe-829b-11e8-96b3-bf43fb45e3e9.png">

Can you help me ? Thanks !

**Comment by pchelk1n** [comment]
Read the error text. Your selectedDate is null.

**Comment by lyrixx** [comment]
@pchelk1n Nope, this is another issue.

The formatter is null: 

https://github.com/twigphp/Twig-extensions/blob/master/lib/Twig/Extensions/Extension/Intl.php#L64

@fjude What version of PHP are you using + what version of this lib are you using ?

**Comment by fjude** [comment]
@pchelk1n Thanks, I know how to read and analyse errors.

@lyrixx : PHP 7.1.15 / TwigExtension 1.5.1

**Comment by lyrixx** [comment]
@fjude Could you try [this PR](https://github.com/twigphp/Twig-extensions/pull/219) ?

**Comment by fjude** [comment]
It's OK with the PR.

**Comment by fabpot** [comment]
v1.5.2 is out now.
