### ISSUE TITLE
time_diff on same datetime

### ISSUE THREAD

**Issue by IndraGunawan** [twigphp/Twig-extensions#231]
Using `time_diff` filter when no time difference it will return empty string.

on KnpTimeBundle it will return `now` message.
https://github.com/KnpLabs/KnpTimeBundle/blob/dd7ed9e72e8c28edb596c13e3d3c18c29d1248b4/DateTimeFormatter.php#L50

**Comment by neufeind** [comment]
In the empty case it don't use diff.ago.* or diff.in.* but diff.empty instead.
https://github.com/KnpLabs/KnpTimeBundle/blob/dd7ed9e72e8c28edb596c13e3d3c18c29d1248b4/Resources/translations/time.en.xliff

**Comment by danielroehrig-mm** [comment]
I think, Indra is right. In case we have zero seconds difference between two time stamps, the diff method will simply return an empty string, not "diff.empty". One easy hack would be to change line 80 in Date.php from `return '';` to `return 'diff.empty;'`

**Comment by fabpot** [comment]
This repository is now abandoned. See #259.
