### ISSUE TITLE
time_diff - wrong result

### ISSUE THREAD

**Issue by axzx** [twigphp/Twig-extensions#232]
date now: `2018-12-03 13:05`

```twig
{{ '2018-12-01 21:03'|date|time_diff }}
```

result:
`diff.ago.day` with params `"%count%" => 1`

I think it should be `"%count%" => 2`

**Comment by stof** [comment]
Well, there is less than 2 days between these two datetimes here. So the implementation is not actually wrong.

On a side node, using the date formatting filter here does not really make sense. I think you either meant to use the `date()` *function* (to convert your string to a `DateTime` instance) or nothing (as `time_diff` will call this function internally if receiving a string). Converting the string to a DateTime to format it again as a string (which will be parsed again by `time_diff`) does not really make sense.

**Comment by axzx** [comment]
I had a wrongly translated phrase:
```
<trans-unit id="3">
    <source>diff.ago.day</source>
    <target>yesterday|%count% days ago|%count% days ago</target>
</trans-unit>
```
Should be `%count% day ago` instead of `yesterday`.
