### ISSUE TITLE
DateExtension does nothing but print "diff.***.***" 

### ISSUE THREAD

**Issue by dougie84mo** [twigphp/Twig-extensions#237]
Read all the instructions on this and how to use these extensions, however the DateExtension explanation is almost useless. Anything i try only prints out "diff.ago.day". Something about adding a translatable interface but im sure that is nonsense because doing exactly what the instructions say is useless to me. Please help, Im not using translations yet.

**Comment by sstok** [comment]
Can you provide more information about your usage? Are using the Extension as part of the Symfony framework (or any other framework for that matter) or as a stand alone. And if so can you can provide a short code snippet that gives this result?

**Comment by chiqui3d** [comment]
The same thing happens to me, result: diff.in.month, lol,
I suppose it has to do with the translations, but I see nothing or no explanation on how to apply it, I also tried to put it in my message.es.yaml and it doesn't work either.

**Comment by chiqui3d** [comment]
80% of the Symfony bundles are dead, I've been with Symfony for a year and what I've learned is that you can't install any, everyone has a problem or a lot of misinformation, as I'm going to Laravel head on.

**Comment by javiereguiluz** [comment]
@chiqui3d you are right. Most of Symfony bundles are no longer maintained ... but that's not a bad thing. Look for topics like "news bundle", "RSS bundle", "Guzzle bundle", etc. You'll find tens of bundles for each of them. That's not sustainable; that's not needed. They could all disappear and nothing bad would happen.

You'll find the same fragmentation and lack of maintenance in every big ecosystem, including the framework you mentioned.

To end with a positive comment about this:

* Symfony provides more features than other frameworks, so you need less packages for it. For example, to "associate roles and permissions with users", you don't need to install anything on Symfony (it's included by default). In other frameworks (e.g. the one you mentioned) you need to install a third-party package.
* The most important and complex bundles are pretty well maintained (DB-related, admin-related, API-related, etc.)
* The strongest part of Symfony is its ecosystem, not necessarily its bundles. For example, Sylius is not exactly "a bundle" ... but it's an amazing project which is taking the e-commerce world by storm. Also, as you can see here: https://symfony.com/projects most important PHP projects use Symfony components. What you learn in Symfony, it can be leveraged in many other projects (e.g. the Symfony Console is the standard to create CLI apps, the HttpFoundation Request+Response is much more used than the PSR-7 standard, etc.)

**Comment by chiqui3d** [comment]
Thank you Javier for your words in which you are right, Symfony you have more good things than bad, the only bad thing for me has been this, which has really been painful than most of the Bundles I installed in the end I ended up uninstalling or doing what I did, better or worse, but I've done it myself, is what I gained with this because I learn more.
But it hurts me as a person that these things happen in such a big framework and I end up saying things like the ones I've said, but I keep working to learn as much as possible, and be able to publish my own bundle, instead of having to say these things.

I'm sorry for my bad words, but I had to say it, but more for a bundle that is maintained by the creator of Symfony.

**Comment by dougie84mo** [comment]
@javiereguiluz well said. More systems like that get absorbed into symfony all the time. I'm going to stick with symfony for sure. If i have to write my on functions its no big deal. 

@sstok Please see my code, if any of this helps. Im persisting using doctrine.

HTML
`Last Updated At: <small>{{ p.updatedAt|time_diff }}</small>`


PHP
```
<?php
/**
     * @var \DateTime
     * @ORM\Column(type="datetime")
     */
    protected $updatedAt;

/**
     * @ORM\PreUpdate
     */
    public function onPreUpdate()
    {
        $this->updatedAt = DT::now();
    }


public function getUpdatedAt()
    {
        return $this->updatedAt;
    }
```
