### ISSUE TITLE
Bug: Extending Twig_TokenParser is deprecated since Twig 2.7 and throws warnings

### ISSUE THREAD

**Issue by MyIgel** [twigphp/Twig-extensions#239]
This affects `Twig_Extensions_TokenParser_Trans` and `Twig_Extensions_SimpleTokenParser`

**Comment by stof** [comment]
Work is already in progress in #236 

@fabpot should we extract the switch to Twig namespaced classes to apply it in 1.x too ?

**Comment by MyIgel** [comment]
That would be great and allow me to use proper namespaces with Twig 2.6

**Comment by theravel** [comment]
Can you prioritize this please?
As long as Twig 2.6 is considered "no more secure" by automatic checks (see https://github.com/FriendsOfPHP/security-advisories/commit/e5783d311652734a691e7606883461f3c48d6728), everybody should switch to Twig 2.7, which is incompatiblew with Twig-extensions...

**Comment by fabpot** [comment]
I think we need to work on a pull request to switch to namespaced classes in 1.x Anyone willing to work on it?

**Comment by MyIgel** [comment]
> Anyone willing to work on it?

I would like to try but I have no idea how to start and how to implement it in a way that nothing breaks :D

**Comment by MyIgel** [comment]
> In a way that nothing breaks

Imho a possible solution could be to require at least twig/twig ^1.38 which is the first 1.* version with baa70287f5b8eff6d90c5779f82088379ebf94a4 which removes the
```php
class AbstractTokenParser extends \Twig_TokenParser
```
dependency so that 
```php
class Twig_Extensions_TokenParser_Trans extends AbstractTokenParser
```
should work?

Or did I missed something? Would be that version "bump" acceptable?

**Comment by fabpot** [comment]
Bumping the min version is possible.

**Comment by MyIgel** [comment]
Another problem is that changing the code to implement the `TokenParserInterface` means to implement another interface which means that for example `parse(Twig_Token $token)` needs to be changed to `parse(\Twig\Token $token)` which would potentially break projects using it?

**Comment by fabpot** [comment]
Fixed in master (will be 2.0 soon).

**Comment by theravel** [comment]
Do you have estimate when 2.0 will be available?

**Comment by MyIgel** [comment]
At least a pre release would be nice :D

Is there a list of blocking ToDo points for releasing 2.0? Maybe we could help solving them?

**Comment by fabpot** [comment]
This repository has been deprecated now. See https://github.com/twigphp/Twig-extensions/blob/master/README.rst
