### ISSUE TITLE
Deprecation Warning for Text.php & Fix

### ISSUE THREAD

**Issue by emovere** [twigphp/Twig-extensions#243]
**Deprecation Warning:**
`Using the "Twig_Extension" class is deprecated since Twig version 2.7, use "Twig\Extension\AbstractExtension" instead.`

**Fix:**
File:
`twig/extensions/lib/Twig/Extensions/Extension/Text.php:`
Old line:
`class Twig_Extensions_Extension_Text extends Twig_Extension`
New line:
`class Twig_Extensions_Extension_Text extends Twig\Extension\AbstractExtension`

Would be great if you could change that!
Thanks for your Library!

**Comment by fabpot** [comment]
Fixed in master (will be 2.0 soon).
