### ISSUE TITLE
Feature: Iterable test functions

### ISSUE THREAD

**Issue by Hanmac** [twigphp/Twig-extensions#245]
Hi i don't know if it should be added into Twig Core or into Twig Extensions, also i don't know if that should be Filters or Tests, but i would like something like filter, that takes an array and a arrow function, and returns true if the arrow evaluates truely

- any = returns true if one in the array arrows to truely
- all = returns false if one in the array arrows to falsely
- one = only one of them can be truely
- none = returns false if one in the array arrows to truely

The goal is to give the arrow an expensive expression that is only run if needed

**Comment by fabpot** [comment]
This has more or less be implemented in Twig core.
