### ISSUE TITLE
Unexpected result of the localizeddate function

### ISSUE THREAD

**Issue by yankielap** [twigphp/Twig-extensions#253]
Using the following format some dates of the end of the year 2019 are rendered as of 2020

{{ my_date | localizeddate('none', 'none', 'es', 'America/Manaus', 'dd/MM/YYYY') }}

Real date -> Date rendered
2019-12-30 13:03:06.0 America/Caracas (-04:00) -> 30/12/2020
2019-12-31 13:04:02.0 America/Caracas (-04:00) -> 31/12/2020

At the moment this has only happened with the month of December 2019.

**Comment by fabpot** [comment]
This repo will be deprecated soon, you should switch to `twig/intl-extra` for intl features.
