### ISSUE TITLE
How to add IntlExtension with release 1.5.4

### ISSUE THREAD

**Issue by bnbc** [twigphp/Twig-extensions#255]
Hello, 

I install the last release of your module in Symfony 4 who delete the file twig_extensions.yml.

But in this file i added Twig\Extensions\IntlExtension support like that : 
`
services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true

    Twig\Extensions\IntlExtension: ~
`

How to add IntlExtension now ? i try in services.yaml file but i get Unknown "localizeddate" filter error

Thks for your help

**Comment by bnbc** [comment]
it's ok not a problem from your module :)

**Comment by alessandrofilira** [comment]
@bnbc How did you solve it? I've same problem but it looks like Symfony ignores configuration. Thanks.

**Comment by bnbc** [comment]
Just create again file twig_extensions.yaml in config/packages : 

[translation.yaml.txt](https://github.com/twigphp/Twig-extensions/files/4164785/translation.yaml.txt)

**Comment by alessandrofilira** [comment]
Thanks for answer, maybe you attached wrong file. I have twig_extensions.yaml, it's the autogenerated version and I uncommented the line with IntlExtension but it doesn't work. Probably some miss configuration. I use a bad workaround but I'd like use right method.
