### ISSUE TITLE
Cannot combine form vars and filter

### ISSUE THREAD

**Issue by Schyzophrenic** [twigphp/Twig-extensions#256]
Hello, 
It seems we cannot combine form variables and the currency_symbol filter for an odd reason. 
Here are some working examples:
`{{ 'EUR'|currency_symbol }}`  > Displays €

`{{ 'form.currency.vars.value }}` > Displays EUR

Unfortunately the follwing generates an exception (I just could not pin point why)
`{{ form.currency.vars.value|currency_symbol }}`

> An exception has been thrown during the rendering of a template ("Couldn't read the indices [Names][][0] for the locale "fr" in "D:\dev\apps\i-wish\vendor\symfony\intl/Resources/data/currencies". The indices also couldn't be found for the fallback locale(s) "en", "root".").

**Comment by fabpot** [comment]
This repo will be deprecated soon, you should switch to `twig/intl-extra` for intl features.

**Comment by Schyzophrenic** [comment]
Thank you @fabpot . I am actually referring to the `twig/intl-extra` and will repost in the proper repository.

**Comment by Schyzophrenic** [comment]
@fabpot I now remember why I created this issue here. It seems I cannot create an issue on `twig/intl-extra` as the tab does not appear. 
Would you be able to set this up please? 
Thank you

**Comment by stof** [comment]
the original source of the intl-extra package is in the main Twig repo (as all other `-extra` packages). The other repos are read-only subtree splits created for composer.

**Comment by Schyzophrenic** [comment]
I didn't realize that, thank you @stof , I'll post the issue there then.
