### ISSUE TITLE
Conflits with doctrine-bundle

### ISSUE THREAD

**Issue by qdequippe** [twigphp/Twig-extensions#262]
Hi,

When I try to install `twig/extensions` (v1.5) with `twig/twig` (v3.0.0) I have this error:

```
Using version ^1.5 for twig/extensions
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Restricting packages listed in "symfony/symfony" to "4.4.*"
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install twig/extensions v1.5.4
    - Conclusion: don't install twig/extensions v1.5.3
    - Conclusion: don't install twig/extensions v1.5.2
    - Conclusion: don't install twig/extensions v1.5.1
    - Conclusion: remove doctrine/doctrine-bundle 2.0.2
    - Conclusion: don't install doctrine/doctrine-bundle 2.0.2
    - twig/twig v1.27.0 conflicts with doctrine/doctrine-bundle[2.0.2].
    - twig/twig v1.28.0 conflicts with doctrine/doctrine-bundle[2.0.2].
...
   - Conclusion: don't install twig/twig v3.0.0|install twig/twig v1.27.0|install twig/twig v1.28.0|install twig/twig v1.28.1|install twig/twig v1.28.2|install twig/twig v1.29.0|install twig/twig v1.30.0|install twig/twig v1.31.0|install twig/twig v1.32.0|install twig/twig v1.33.0|install twig/twig v1.33.1|install twig/twig v1.33.2|install twig/twig v2.0.0|install twig/twig v2.1.0|install twig/twig v2.2.0|install twig/twig v2.3.0|install twig/twig v2.3.1|install twig/twig v2.3.2
```

I don't know if this problem comes from twig/extensions, twig/twig v3 or doctrine-bundle

**Comment by dfridrich** [comment]
Same problem here. My temporary solution: downgrade Twig `composer req twig/twig:"^2.12"`

**Comment by fabpot** [comment]
You should migrate away from twig/extensions as it is going to be deprecated soon. Most of the features are now part of Twig 2/3. See the updated README file: https://github.com/twigphp/Twig-extensions/blob/master/README.rst

**Comment by Shade634** [comment]
@fabpot I am also running into this, im still quite new to Symfony and the documentation is outdated then as well: https://symfony.com/doc/current/templating/twig_extension.html 
Can this please be corrected with what should be used instead?

` composer require twig/extensions`

**Comment by stof** [comment]
`composer require twig/extra-bundle twig/intl-extra` (or whatever other Twig extra package you want to use)

Regarding the outdated doc, please open an issue on https://github.com/symfony/symfony-docs
