### ISSUE TITLE
Alternative for Date time_diff ?

### ISSUE THREAD

**Issue by Soonz** [twigphp/Twig-extensions#264]
Is it planned to create an alternative to time_diff for Symfony 5 ?

Thanks.

**Comment by fabpot** [comment]
No. But I encourage the community to create one based on the code here and publish it on Packagist.

**Comment by Soonz** [comment]
I don't really want to reopen this issue, I just wanted to share this for the people who needs an alternative : https://github.com/KnpLabs/KnpTimeBundle

Maybe you can edit the readme and suggest this as an alternative. Thanks.
