### ISSUE TITLE
Php 7.4 preloading on v1.5.4 fails

### ISSUE THREAD

**Issue by bassim** [twigphp/Twig-extensions#270]
Getting: 

> Error: Cannot redeclare twig_truncate_filter() (previously declared in /xxx/vendor/twig/extensions/lib/Twig/Extensions/Extension/Text.php:39)

When I surround those functions with a 

`if (!function_exists('twig_truncate_filter')) {`

It all starts to work, when running on master branch, all is fine too

**Comment by stof** [comment]
Given that this package is deprecated, I doubt it will be fixed.

**Comment by fabpot** [comment]
This project is not maintained anymore, have a look at the README file for alternatives.
