### ISSUE TITLE
Mark as abandoned on packagist.org

### ISSUE THREAD

**Issue by rgeraads** [twigphp/Twig-extensions#273]
Since this package is abandoned, should it be marked as abandoned on https://packagist.org/packages/twig/extensions so that composer recognises it as being abandoned?

**Comment by shakaran** [comment]
UPDATE: it seems that it is marked as abandoned, but without suggestions for twig/extensions

`Package twig/extensions is abandoned, you should avoid using it. No replacement was suggested.`

It should be suggested as _twig/extra-bundle_  (twig core extra)

`composer require twig/extra-bundle`

**Comment by dvdknaap** [comment]
> UPDATE: it seems that it is marked as abandoned, but without suggestions for twig/extensions
> 
> `Package twig/extensions is abandoned, you should avoid using it. No replacement was suggested.`
> 
> It should be suggested as _twig/extra-bundle_ (twig core extra)
> 
> `composer require twig/extra-bundle`

the twig/extra-bundle is not an replacement that why i have created an pull request for twig 3.0 support #285
