### ISSUE TITLE
What's the alternative solution for i18n translation which is supported by twig/twig-extension before and is not supported after upgrading to twig/twig:3

### ISSUE THREAD

**Issue by tripbnb66** [twigphp/Twig-extensions#274]
We use twig/twig-extension to do the international and localtion(i18n/i10n).
For example:
`<a href="/logout.php">{% trans "Logout" %}</a>`
You can see that we can use "trans" keyword to iimplment translation and also support gettext for generating .po and .mo files.

Now, as the tw/twig-extension doesn't support twig/twig3, what we can do if we use the "trans" command to do the translation.

Cany anyone who has the same problem like me and share your solution to me?
Thank you so much.

**Comment by JBlond** [comment]
You can use https://github.com/JBlond/twig-trans

**Comment by dvdknaap** [comment]
@tripbnb66 I've created a pull request with twig 3 support see #285

**Comment by fabpot** [comment]
I'd recommend to create a new library.
