### ISSUE TITLE
Better i18n extension (based on Symfony)?

### ISSUE THREAD

**Issue by jhogervorst** [twigphp/Twig-extensions#51]
I created the [Twi18n extension](https://github.com/jhogervorst/Twi18n) that uses Symfony's Translation component with PHP's get text as data source. See the documentation for more information on the functionality.

Is this something you guys would like to see in this extension repository? If yes, I'd be happy to make a fork and add the required files.

**Comment by deadbeef84** [comment]
+1
Custom text domains would be useful.
