### ISSUE TITLE
add a base64 encoding filter

### ISSUE THREAD

**Issue by lsmith77** [twigphp/Twig-extensions#54]
this can be convenient for inlining images. the filter should accept a variable containing a binary string, a stream resource and maybe also just a filename.

**Comment by damienalexandre** [comment]
:+1:  for this feature in the core!

**Comment by JHGitty** [comment]
:+1:

**Comment by webdevilopers** [comment]
:+1:

**Comment by Maelstromeous** [comment]
👍

**Comment by nateclonch** [comment]
👍

**Comment by obax** [comment]
👍

**Comment by fabpot** [comment]
implemented in Twig core (see twigphp/twig#3102)
