### ISSUE TITLE
url_decode?

### ISSUE THREAD

**Issue by umpirsky** [twigphp/Twig-extensions#60]
I needed `url_decode` few days ago, but there is only [url_encode](http://twig.sensiolabs.org/doc/filters/url_encode.html) in Twig.

Any reason not to have that? Can we have it in this project or in Twig?

**Comment by Arkemlar** [comment]
url_decode usful to make go-back links:
link to edit page: `{{ path('whatever', {entityName: entity.id, referer: app.request.uri|url_encode}) }}`
go-back link: `{{ app.request.get('referer')|url_decode }}`

**Comment by umpirsky** [comment]
I used https://github.com/umpirsky/twig-php-function for this.

**Comment by Spomsoree** [comment]
It would have helped me add a siteLink for example:
```
<script type="application/ld+json">
    {
      "@context": "https://schema.org",
      "@type": "WebSite",
      ...
        "target": "https://query.example.com/search?q={search_term_string}",
        "query-input": "required name=search_term_string"
      }
    }
    </script>
```

I used the symfony url function to generate the target link. Without `url_decode`, this does not seem to be possible.
