### ISSUE TITLE
Translating plurals

### ISSUE THREAD

**Issue by umpirsky** [twigphp/Twig-extensions#70]
According to [docs](http://twig.sensiolabs.org/doc/extensions/i18n.html#usage) plural translations should be defined as:

```
{% trans %}
    I have one apple.
{% plural apple_count %}
    I have {{ count }} apples.
{% endtrans %}
```

I'm using [Twig Gettext Extractor](https://github.com/umpirsky/Twig-Gettext-Extractor) to extract translations (it just forces twig to `loadTemplate`), but for some reason, variables are extracted like `%count%` instead `{{ count }}`, which produces untranslated messages. 

I tried changing template to:

```
{% trans %}
    I have one apple.
{% plural apple_count %}
    I have %coun% apples.
{% endtrans %}
```

but then `%coun%` is not replaced with actual variable value.

I used `transhoice` and it worked, but I like this plural tag more because it has better poedit integration.

More then that, when I enable `Twig_Extensions_Extension_I18n` in my Silex app `$app['twig']->addExtension(new \Twig_Extensions_Extension_I18n())` I get:

`Warning: gettext() expects exactly 1 parameter, 3 given in resources/cache/twig/70/d7/fd80c73ce0b5c01ac2dc57367f74.php on line 401`

Part of d7/fd80c73ce0b5c01ac2dc57367f74.php:

``` php
echo ">";
echo twig_escape_filter($this->env, gettext($this->getContext($context, "label"), array(), $this->getContext($context, "translation_domain")), "html", null, true); // #401
echo "</label>
```

This warning happens for each label translated in my form.

**Comment by fabpot** [comment]
I'm closing all issues/PRs on the i18n extension as I don't use it and I don't have time to maintain it anymore. This repository will be soon deprecated in favor of the `twig/*-extra` packages, but i18n wont be transferred. If anyone wants to work on the i18n extension, I would recommend to take the code from here and host it on a new repository.
