### ISSUE TITLE
trans with key value and variable

### ISSUE THREAD

**Issue by Bacteries** [twigphp/Twig-extensions#74]
Hi,
I use Twig and Twig Extensions (in a non Symfon2 env) and I use key value for my translation.

So I have done this : 

```
{{ "auth.loggedAs"|trans({'%userName%' : user.name}) }}
```

But it doesn't work : 

```
gettext() expects exactly 1 parameter, 2 given
```

I check the extension and I guess it's because variable are change in a string, but there is no way to translate using placeholder.
Am I wrong?
(and if you know an extension that can do this?)

Thanks.

**Comment by stof** [comment]
The gettext-based trans filter does not support placeholders like the Symfony translation extension does. Don't confuse both (even though they both use ``|trans``, which is very unfortunate IMO)
